# Generated by Django 5.0.3 on 2024-03-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_grant"),
    ]

    operations = [
        migrations.AddField(
            model_name="grant",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("done", "Done")],
                default="pending",
                max_length=128,
            ),
        ),
    ]
