# Generated by Django 5.0.3 on 2024-03-20 12:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_remove_grant_is_active_remove_grant_need_to_remove_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="application",
            options={
                "permissions": (
                    ("can_approve_application", "Can_approve_application"),
                ),
                "verbose_name": "заявка",
                "verbose_name_plural": "заявки",
            },
        ),
        migrations.AlterModelOptions(
            name="grant",
            options={
                "verbose_name": "право доступа",
                "verbose_name_plural": "права доступа",
            },
        ),
    ]
