# Generated by Django 5.0.3 on 2024-03-21 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_application_options_alter_grant_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="invite_status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("success", "Success")],
                default="pending",
                max_length=64,
            ),
        ),
        migrations.CreateModel(
            name="InvitationToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        unique=True,
                        verbose_name="Токен приглашения",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                ("expired_at", models.DateTimeField(verbose_name="Дата истечения")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Токен приглашения",
                "verbose_name_plural": "Токены приглашения",
                "unique_together": {("user", "token")},
            },
        ),
    ]
