# Generated by Django 5.0.3 on 2024-03-25 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_user_invite_status_invitationtoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="grant",
            name="application",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.application",
            ),
        ),
    ]
