# Generated by Django 5.0.3 on 2024-03-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_grant_application"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="scope",
            field=models.IntegerField(
                choices=[(0, "In process"), (1, "Approved"), (2, "Resolved")], default=0
            ),
        ),
    ]
