# Generated by Django 5.0.3 on 2024-03-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_application_scope"),
    ]

    operations = [
        migrations.AddField(
            model_name="grant",
            name="scope",
            field=models.CharField(
                choices=[(0, "Read Scope"), (1, "Read and write scopes")], default=0
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="scope",
            field=models.IntegerField(
                choices=[(0, "Read Scope"), (1, "Read and write scopes")], default=0
            ),
        ),
    ]
