# Generated by Django 5.0.3 on 2024-03-30 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_grant_scope_alter_application_scope"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grant",
            name="scope",
            field=models.IntegerField(
                choices=[(0, "Read Scope"), (1, "Read and write scopes")], default=0
            ),
        ),
        migrations.CreateModel(
            name="Command",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("executing_command", models.TextField()),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.resource"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
