# Generated by Django 5.0.3 on 2024-03-30 19:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_alter_command_options_command_command_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="command",
            old_name="executing_command",
            new_name="executing_pattern",
        ),
    ]
