# Generated by Django 5.0.3 on 2024-03-31 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_resource_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="url",
            field=models.CharField(
                help_text="URL ресурса(необходим если хотите выполнять команды, например отправлять запросы в БД)",
                null=True,
            ),
        ),
    ]
