# Generated by Django 5.0.3 on 2024-03-31 19:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_alter_resource_url"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Command",
            new_name="CommandPattern",
        ),
    ]
