# Generated by Django 5.0.3 on 2024-04-03 14:43

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_rename_command_commandpattern"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schema_name",
                    models.CharField(
                        db_index=True,
                        max_length=63,
                        unique=True,
                        validators=[
                            django_tenants.postgresql_backend.base._check_schema_name
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "admin_email",
                    models.EmailField(
                        blank=True,
                        default=None,
                        max_length=254,
                        null=True,
                        verbose_name="Email админа тенанта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказчик",
                "verbose_name_plural": "Заказчики",
            },
        ),
        migrations.CreateModel(
            name="TenantCreationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant_name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="имя тенанта"
                    ),
                ),
                (
                    "domain",
                    models.CharField(max_length=253, unique=True, verbose_name="домен"),
                ),
                (
                    "admin_email",
                    models.EmailField(max_length=254, verbose_name="email админа"),
                ),
            ],
            options={
                "verbose_name": "Запрос на создание тенанта",
                "verbose_name_plural": "Запросы на создание тенанта",
            },
        ),
        migrations.AlterModelOptions(
            name="commandpattern",
            options={
                "verbose_name": "Шаблон скрипта",
                "verbose_name_plural": "Шаблоны скриптов",
            },
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(db_index=True, max_length=253, unique=True),
                ),
                ("is_primary", models.BooleanField(db_index=True, default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Адрес заказчика",
                "verbose_name_plural": "Адреса заказчиков",
            },
        ),
    ]
