# Generated by Django 5.0.3 on 2024-04-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_tenant_tenantcreationrequest_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="commands",
            field=models.ManyToManyField(
                null=True, related_name="resource_commands", to="core.commandpattern"
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="url",
            field=models.CharField(
                blank=True,
                help_text="URL ресурса(необходим если хотите выполнять команды, например отправлять запросы в БД)",
                null=True,
            ),
        ),
    ]
