# Generated by Django 5.0.3 on 2024-04-04 16:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_alter_resource_commands_alter_resource_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resource",
            name="url",
        ),
    ]
