# Generated by Django 5.0.3 on 2024-04-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_remove_resource_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_id",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="ID в телеграме"
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="commands",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="resource_commands",
                to="core.commandpattern",
            ),
        ),
    ]
