# Generated by Django 5.0.3 on 2024-04-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_tenant_telegram_bot_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="resource_url",
            field=models.CharField(blank=True, null=True),
        ),
    ]
